//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advanced_Lock.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Advanced_Lock.Translations.de", typeof(de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinzufügen.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alles verschlüsseln und entschlüsseln.
        /// </summary>
        internal static string Application_description {
            get {
                return ResourceManager.GetString("Application description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stornieren.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprachen ändern.
        /// </summary>
        internal static string Change_languages {
            get {
                return ResourceManager.GetString("Change languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überprüfen.
        /// </summary>
        internal static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Konfiguration wurde überprüft und alle Probleme wurden behoben.
        /// </summary>
        internal static string Checked_configuration_and_fixed_problems {
            get {
                return ResourceManager.GetString("Checked configuration and fixed problems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufbau.
        /// </summary>
        internal static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dunkler Modus.
        /// </summary>
        internal static string Dark_Mode {
            get {
                return ResourceManager.GetString("Dark Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entschlüsseln.
        /// </summary>
        internal static string Decrypt {
            get {
                return ResourceManager.GetString("Decrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entschlüsselungsdatei.
        /// </summary>
        internal static string Decryption_File {
            get {
                return ResourceManager.GetString("Decryption File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entschlüsselungsordner.
        /// </summary>
        internal static string Decryption_Folder {
            get {
                return ResourceManager.GetString("Decryption Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entschlüsselungstext.
        /// </summary>
        internal static string Decryption_Text {
            get {
                return ResourceManager.GetString("Decryption Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesamten Verlauf löschen.
        /// </summary>
        internal static string Delete_All_History {
            get {
                return ResourceManager.GetString("Delete All History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeile löschen.
        /// </summary>
        internal static string Delete_Row {
            get {
                return ResourceManager.GetString("Delete Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designer und Entwickler: MjavadH
        ///Dies ist eine Open-Source-Software
        ///GitHub:.
        /// </summary>
        internal static string Developer_Description {
            get {
                return ResourceManager.GetString("Developer Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort aktivieren.
        /// </summary>
        internal static string Enable_password {
            get {
                return ResourceManager.GetString("Enable password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verschlüsseln.
        /// </summary>
        internal static string Encrypt {
            get {
                return ResourceManager.GetString("Encrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verschlüsselungsdatei.
        /// </summary>
        internal static string Encryption_File {
            get {
                return ResourceManager.GetString("Encryption File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verschlüsselungsordner.
        /// </summary>
        internal static string Encryption_Folder {
            get {
                return ResourceManager.GetString("Encryption Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verschlüsselungstext.
        /// </summary>
        internal static string Encryption_Text {
            get {
                return ResourceManager.GetString("Encryption Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geben Sie das Passwort ein.
        /// </summary>
        internal static string Enter_password {
            get {
                return ResourceManager.GetString("Enter password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler: Das Feld „Ihre Wahl“ oder „Passwort“ ist leer.
        /// </summary>
        internal static string Error_password_or_your_choice {
            get {
                return ResourceManager.GetString("Error password or your choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beispielbenachrichtigung.
        /// </summary>
        internal static string Example_Notification {
            get {
                return ResourceManager.GetString("Example Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Export ist abgeschlossen.
        /// </summary>
        internal static string Export_is_done {
            get {
                return ResourceManager.GetString("Export is done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordner.
        /// </summary>
        internal static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Import ist abgeschlossen.
        /// </summary>
        internal static string Import_is_done {
            get {
                return ResourceManager.GetString("Import is done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in Iran.
        /// </summary>
        internal static string in_iran {
            get {
                return ResourceManager.GetString("in iran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falsches Passwort!.
        /// </summary>
        internal static string Incorect_Password {
            get {
                return ResourceManager.GetString("Incorect Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verlauf laden.
        /// </summary>
        internal static string Load_History {
            get {
                return ResourceManager.GetString("Load History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gemacht mit.
        /// </summary>
        internal static string Made_with {
            get {
                return ResourceManager.GetString("Made with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speisekarte.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei nicht gefunden.
        /// </summary>
        internal static string Not_found_file {
            get {
                return ResourceManager.GetString("Not found file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort ist aktiviert.
        /// </summary>
        internal static string password_is_enable {
            get {
                return ResourceManager.GetString("password is enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ton abspielen.
        /// </summary>
        internal static string Play_sound {
            get {
                return ResourceManager.GetString("Play sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualisierung.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entfernen.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starten Sie die Anwendung neu, um die Sprache zu ändern.
        /// </summary>
        internal static string Restart_app_to_chenge_language {
            get {
                return ResourceManager.GetString("Restart app to chenge language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starten Sie die Anwendung neu, um das Thema zu ändern.
        /// </summary>
        internal static string Restart_app_to_chenge_theme {
            get {
                return ResourceManager.GetString("Restart app to chenge theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ergebnis.
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ergebnistext kopiert.
        /// </summary>
        internal static string Result_text_copyed {
            get {
                return ResourceManager.GetString("Result text copyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Ergebnistext ist leer.
        /// </summary>
        internal static string Result_text_empty {
            get {
                return ResourceManager.GetString("Result text empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verlauf speichern.
        /// </summary>
        internal static string Save_History {
            get {
                return ResourceManager.GetString("Save History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benachrichtigung anzeigen.
        /// </summary>
        internal static string Show_notification {
            get {
                return ResourceManager.GetString("Show notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einreichen.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Konfiguration der Software ist kein Problem.
        /// </summary>
        internal static string There_is_no_problem_in_configuring {
            get {
                return ResourceManager.GetString("There is no problem in configuring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deine Entscheidung.
        /// </summary>
        internal static string your_choice {
            get {
                return ResourceManager.GetString("your choice", resourceCulture);
            }
        }
    }
}
