//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advanced_Lock.String {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ar() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Advanced_Lock.String.ar", typeof(ar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تشفير وفك تشفير أي شيء.
        /// </summary>
        internal static string Application_description {
            get {
                return ResourceManager.GetString("Application description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلغاء.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغيير اللغات.
        /// </summary>
        internal static string Change_languages {
            get {
                return ResourceManager.GetString("Change languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحقق.
        /// </summary>
        internal static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحقق من التكوين.
        /// </summary>
        internal static string Check_configuration {
            get {
                return ResourceManager.GetString("Check configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم فحص التكوين وتم إصلاح جميع المشكلات.
        /// </summary>
        internal static string Checked_configuration_and_fixed_problems {
            get {
                return ResourceManager.GetString("Checked configuration and fixed problems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوضع الداكن.
        /// </summary>
        internal static string Dark_Mode {
            get {
                return ResourceManager.GetString("Dark Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فك تشفير.
        /// </summary>
        internal static string Decrypt {
            get {
                return ResourceManager.GetString("Decrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملف فك التشفير.
        /// </summary>
        internal static string Decryption_File {
            get {
                return ResourceManager.GetString("Decryption File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجلد فك التشفير.
        /// </summary>
        internal static string Decryption_Folder {
            get {
                return ResourceManager.GetString("Decryption Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نص فك التشفير.
        /// </summary>
        internal static string Decryption_Text {
            get {
                return ResourceManager.GetString("Decryption Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف كافة المحفوظات.
        /// </summary>
        internal static string Delete_All_History {
            get {
                return ResourceManager.GetString("Delete All History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to احذف صف.
        /// </summary>
        internal static string Delete_Row {
            get {
                return ResourceManager.GetString("Delete Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المصمم والمطور: MjavadH
        ///هذا برنامج مفتوح المصدر
        ///GitHub:.
        /// </summary>
        internal static string Developer_Description {
            get {
                return ResourceManager.GetString("Developer Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمكين كلمة المرور.
        /// </summary>
        internal static string Enable_password {
            get {
                return ResourceManager.GetString("Enable password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تشفير.
        /// </summary>
        internal static string Encrypt {
            get {
                return ResourceManager.GetString("Encrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملف التشفير.
        /// </summary>
        internal static string Encryption_File {
            get {
                return ResourceManager.GetString("Encryption File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجلد التشفير.
        /// </summary>
        internal static string Encryption_Folder {
            get {
                return ResourceManager.GetString("Encryption Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نص التشفير.
        /// </summary>
        internal static string Encryption_Text {
            get {
                return ResourceManager.GetString("Encryption Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل كلمة المرور.
        /// </summary>
        internal static string Enter_password {
            get {
                return ResourceManager.GetString("Enter password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ: الحقل &quot;اختيارك&quot; أو &quot;كلمة المرور&quot; فارغ.
        /// </summary>
        internal static string Error_password_or_your_choice {
            get {
                return ResourceManager.GetString("Error password or your choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مثال للإخطار.
        /// </summary>
        internal static string Example_Notification {
            get {
                return ResourceManager.GetString("Example Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التصدير.
        /// </summary>
        internal static string Export_is_done {
            get {
                return ResourceManager.GetString("Export is done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملف.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجلد.
        /// </summary>
        internal static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الاستيراد.
        /// </summary>
        internal static string Import_is_done {
            get {
                return ResourceManager.GetString("Import is done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to في إيران.
        /// </summary>
        internal static string in_iran {
            get {
                return ResourceManager.GetString("in iran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة سر خاطئة!.
        /// </summary>
        internal static string Incorect_Password {
            get {
                return ResourceManager.GetString("Incorect Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومة.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضع الضوء.
        /// </summary>
        internal static string Light_Mode {
            get {
                return ResourceManager.GetString("Light Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ التحميل.
        /// </summary>
        internal static string Load_History {
            get {
                return ResourceManager.GetString("Load History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مصنوع من.
        /// </summary>
        internal static string Made_with {
            get {
                return ResourceManager.GetString("Made with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة طعام.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم العثور على الملف.
        /// </summary>
        internal static string Not_found_file {
            get {
                return ResourceManager.GetString("Not found file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نعم.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تمكين كلمة المرور.
        /// </summary>
        internal static string password_is_enable {
            get {
                return ResourceManager.GetString("password is enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تشغيل الصوت.
        /// </summary>
        internal static string Play_sound {
            get {
                return ResourceManager.GetString("Play sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ينعش.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أعد تشغيل التطبيق لتغيير اللغة.
        /// </summary>
        internal static string Restart_app_to_chenge_language {
            get {
                return ResourceManager.GetString("Restart app to chenge language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أعد تشغيل التطبيق لتغيير المظهر.
        /// </summary>
        internal static string Restart_app_to_chenge_theme {
            get {
                return ResourceManager.GetString("Restart app to chenge theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نتيجة.
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم نسخ نص النتيجة.
        /// </summary>
        internal static string Result_text_copyed {
            get {
                return ResourceManager.GetString("Result text copyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نص النتيجة فارغ.
        /// </summary>
        internal static string Result_text_empty {
            get {
                return ResourceManager.GetString("Result text empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ التاريخ.
        /// </summary>
        internal static string Save_History {
            get {
                return ResourceManager.GetString("Save History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدد الموضوع الخاص بك.
        /// </summary>
        internal static string Select_your_Theme {
            get {
                return ResourceManager.GetString("Select your Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعدادات.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إظهار الإخطار.
        /// </summary>
        internal static string Show_notification {
            get {
                return ResourceManager.GetString("Show notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يُقدِّم.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نص.
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا توجد مشكلة في تكوين البرنامج.
        /// </summary>
        internal static string There_is_no_problem_in_configuring {
            get {
                return ResourceManager.GetString("There is no problem in configuring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختيارك.
        /// </summary>
        internal static string your_choice {
            get {
                return ResourceManager.GetString("your choice", resourceCulture);
            }
        }
    }
}
